# Generated by Django 4.2.7 on 2023-11-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_subscribers_options_subscribers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='name',
        ),
    ]
