# Generated by Django 4.2.7 on 2023-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='preferred_light',
            field=models.CharField(blank=True, choices=[('Indirect Light', 'Indirect Light'), ('Bright Light', 'Bright Light'), ('Low Light', 'Low Light')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='watering_needs',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
    ]
